#easy_admin:
#    entities:
#        # List the entity class name you want to manage
#        - App\Entity\Product
#        - App\Entity\Category
#        - App\Entity\User

easy_admin:
    entities:
        User:
            class: App\Entity\User
        Subject:
            class: App\Entity\Subject
        Task:
            class: App\Entity\Task
            form:
                fields:
                    - 'title'
                    - 'description'
                    - 'subject'
                    - { property: 'deadlineAt', type: 'date', type_options: { widget: 'single_text' } }
